/* Generate combined index on the run_composition table.*/
use keyruns;
CREATE INDEX combined_index on run_composition(
	mage_arcane,
	mage_fire,
	mage_frost,
	paladin_holy,
	paladin_protection,
	paladin_retribution,
	warrior_arms,
	warrior_fury,
	warrior_protection,
	druid_balance,
	druid_feral,
	druid_guardian,
	druid_restoration,
	death_knight_blood,
	death_knight_frost,
	death_knight_unholy,
	hunter_beast_mastery,
	hunter_marksmanship,
	hunter_survival,
	priest_discipline,
	priest_holy,
	priest_shadow,
	rogue_assassination,
	rogue_outlaw,
	rogue_subtlety,
	shaman_elemental,
	shaman_enhancement,
	shaman_restoration,
	warlock_affliction,
	warlock_demonology,
	warlock_destruction,
	monk_brewmaster,
	monk_windwalker,
	monk_mistweaver,
	demon_hunter_havoc,
	demon_hunter_vengeance);
/* to run: > mysql -u username -p < path-to\scriptName.sql */