branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: zip_these
  branch: null
  default_ec2_keyname: myamazon
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
